//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Iglesia.Prism.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Iglesia.Prism.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept.
        /// </summary>
        internal static string Accept {
            get {
                return ResourceManager.GetString("Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Meeting.
        /// </summary>
        internal static string AddMeeting {
            get {
                return ResourceManager.GetString("AddMeeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Meeting was created successfully.
        /// </summary>
        internal static string AddMeetingMessage {
            get {
                return ResourceManager.GetString("AddMeetingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter an address..
        /// </summary>
        internal static string AddressError {
            get {
                return ResourceManager.GetString("AddressError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your address....
        /// </summary>
        internal static string AddressPlaceHolder {
            get {
                return ResourceManager.GetString("AddressPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new user.
        /// </summary>
        internal static string AddUsers {
            get {
                return ResourceManager.GetString("AddUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adress.
        /// </summary>
        internal static string Adress {
            get {
                return ResourceManager.GetString("Adress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assistances.
        /// </summary>
        internal static string Assistances {
            get {
                return ResourceManager.GetString("Assistances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        internal static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password was changed successfully..
        /// </summary>
        internal static string ChangePassworrdMessage {
            get {
                return ResourceManager.GetString("ChangePassworrdMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User updated..
        /// </summary>
        internal static string ChangeUserMessage {
            get {
                return ResourceManager.GetString("ChangeUserMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Church.
        /// </summary>
        internal static string Church {
            get {
                return ResourceManager.GetString("Church", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select a church..
        /// </summary>
        internal static string ChurchError {
            get {
                return ResourceManager.GetString("ChurchError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select your church....
        /// </summary>
        internal static string ChurchPlaceHolder {
            get {
                return ResourceManager.GetString("ChurchPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm new password.
        /// </summary>
        internal static string ConfirmNewPassword {
            get {
                return ResourceManager.GetString("ConfirmNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter a confirmation for the new password..
        /// </summary>
        internal static string ConfirmNewPasswordError1 {
            get {
                return ResourceManager.GetString("ConfirmNewPasswordError1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password and the confirmation doesn&apos;t match..
        /// </summary>
        internal static string ConfirmNewPasswordError2 {
            get {
                return ResourceManager.GetString("ConfirmNewPasswordError2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the confirmation for the new password....
        /// </summary>
        internal static string ConfirmNewPasswordPlaceHolder {
            get {
                return ResourceManager.GetString("ConfirmNewPasswordPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check the internet connection.
        /// </summary>
        internal static string ConnectionError {
            get {
                return ResourceManager.GetString("ConnectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current password.
        /// </summary>
        internal static string CurrentPassword {
            get {
                return ResourceManager.GetString("CurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter your new password..
        /// </summary>
        internal static string CurrentPasswordError {
            get {
                return ResourceManager.GetString("CurrentPasswordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your current password.....
        /// </summary>
        internal static string CurrentPasswordPlaceHolder {
            get {
                return ResourceManager.GetString("CurrentPasswordPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of meeting.
        /// </summary>
        internal static string DateMeeting {
            get {
                return ResourceManager.GetString("DateMeeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to District.
        /// </summary>
        internal static string District {
            get {
                return ResourceManager.GetString("District", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select a district..
        /// </summary>
        internal static string DistrictError {
            get {
                return ResourceManager.GetString("DistrictError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select your district....
        /// </summary>
        internal static string DistrictPlaceHolder {
            get {
                return ResourceManager.GetString("DistrictPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document.
        /// </summary>
        internal static string Document {
            get {
                return ResourceManager.GetString("Document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter a document..
        /// </summary>
        internal static string DocumentError {
            get {
                return ResourceManager.GetString("DocumentError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your document number....
        /// </summary>
        internal static string DocumentPlaceHolder {
            get {
                return ResourceManager.GetString("DocumentPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter a valid email..
        /// </summary>
        internal static string EmailError {
            get {
                return ResourceManager.GetString("EmailError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your email....
        /// </summary>
        internal static string EmailPlaceHolder {
            get {
                return ResourceManager.GetString("EmailPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User no found..
        /// </summary>
        internal static string Error001 {
            get {
                return ResourceManager.GetString("Error001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A user with that email is already registered..
        /// </summary>
        internal static string Error003 {
            get {
                return ResourceManager.GetString("Error003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Church not found..
        /// </summary>
        internal static string Error004 {
            get {
                return ResourceManager.GetString("Error004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current password is incorrect..
        /// </summary>
        internal static string Error005 {
            get {
                return ResourceManager.GetString("Error005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        internal static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter a first name..
        /// </summary>
        internal static string FirstNameError {
            get {
                return ResourceManager.GetString("FirstNameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your first name....
        /// </summary>
        internal static string FirstNamePlaceHolder {
            get {
                return ResourceManager.GetString("FirstNamePlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot your password?.
        /// </summary>
        internal static string ForgotPassword {
            get {
                return ResourceManager.GetString("ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Camera.
        /// </summary>
        internal static string FromCamera {
            get {
                return ResourceManager.GetString("FromCamera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Gallery.
        /// </summary>
        internal static string FromGallery {
            get {
                return ResourceManager.GetString("FromGallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is present?.
        /// </summary>
        internal static string IsPresent {
            get {
                return ResourceManager.GetString("IsPresent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        internal static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter a last name..
        /// </summary>
        internal static string LastNameError {
            get {
                return ResourceManager.GetString("LastNameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your last name....
        /// </summary>
        internal static string LastNamePlaceHolder {
            get {
                return ResourceManager.GetString("LastNamePlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        internal static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email or password wrong.
        /// </summary>
        internal static string LoginError {
            get {
                return ResourceManager.GetString("LoginError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        internal static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meetings.
        /// </summary>
        internal static string Meetings {
            get {
                return ResourceManager.GetString("Meetings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Members.
        /// </summary>
        internal static string Members {
            get {
                return ResourceManager.GetString("Members", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify user.
        /// </summary>
        internal static string ModifyUser {
            get {
                return ResourceManager.GetString("ModifyUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password.
        /// </summary>
        internal static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter the new password..
        /// </summary>
        internal static string NewPasswordError {
            get {
                return ResourceManager.GetString("NewPasswordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the new password....
        /// </summary>
        internal static string NewPasswordPlaceHolder {
            get {
                return ResourceManager.GetString("NewPasswordPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The device does not support access to the camera..
        /// </summary>
        internal static string NoCameraSupported {
            get {
                return ResourceManager.GetString("NoCameraSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The device does not support access to the gallery..
        /// </summary>
        internal static string NoGallerySupported {
            get {
                return ResourceManager.GetString("NoGallerySupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password confirm.
        /// </summary>
        internal static string PasswordConfirm {
            get {
                return ResourceManager.GetString("PasswordConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter a password confirm..
        /// </summary>
        internal static string PasswordConfirmError1 {
            get {
                return ResourceManager.GetString("PasswordConfirmError1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password and confirm does not match..
        /// </summary>
        internal static string PasswordConfirmError2 {
            get {
                return ResourceManager.GetString("PasswordConfirmError2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the password confirm....
        /// </summary>
        internal static string PasswordConfirmPlaceHolder {
            get {
                return ResourceManager.GetString("PasswordConfirmPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter your password..
        /// </summary>
        internal static string PasswordError {
            get {
                return ResourceManager.GetString("PasswordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your password....
        /// </summary>
        internal static string PasswordPlaceHolder {
            get {
                return ResourceManager.GetString("PasswordPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number.
        /// </summary>
        internal static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your phone....
        /// </summary>
        internal static string PhoneError {
            get {
                return ResourceManager.GetString("PhoneError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter a phone..
        /// </summary>
        internal static string PhonePlaceHolder {
            get {
                return ResourceManager.GetString("PhonePlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Where do you want to take the picture?.
        /// </summary>
        internal static string PictureSource {
            get {
                return ResourceManager.GetString("PictureSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profession.
        /// </summary>
        internal static string Profession {
            get {
                return ResourceManager.GetString("Profession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select a profession..
        /// </summary>
        internal static string ProfessionError {
            get {
                return ResourceManager.GetString("ProfessionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select your profession....
        /// </summary>
        internal static string ProfessionPlaceHolder {
            get {
                return ResourceManager.GetString("ProfessionPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recover Password.
        /// </summary>
        internal static string RecoverPassword {
            get {
                return ResourceManager.GetString("RecoverPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An email was sent to change your password..
        /// </summary>
        internal static string RecoverPasswordMessage {
            get {
                return ResourceManager.GetString("RecoverPasswordMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region.
        /// </summary>
        internal static string Region {
            get {
                return ResourceManager.GetString("Region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select a region..
        /// </summary>
        internal static string RegionError {
            get {
                return ResourceManager.GetString("RegionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select your region....
        /// </summary>
        internal static string RegionPlaceHolder {
            get {
                return ResourceManager.GetString("RegionPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register New User.
        /// </summary>
        internal static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your user has been registered ok, an email was sent to confirm the user account..
        /// </summary>
        internal static string RegisterMessage {
            get {
                return ResourceManager.GetString("RegisterMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search a user....
        /// </summary>
        internal static string SearchAUser {
            get {
                return ResourceManager.GetString("SearchAUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a date to Meeting.
        /// </summary>
        internal static string SelectDate {
            get {
                return ResourceManager.GetString("SelectDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show users of my church.
        /// </summary>
        internal static string ShowUsersByChurch {
            get {
                return ResourceManager.GetString("ShowUsersByChurch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The assistants was updated successfully.
        /// </summary>
        internal static string UpdateAssistancesMessage {
            get {
                return ResourceManager.GetString("UpdateAssistancesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        internal static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
    }
}
